### PR TITLE
Removing users that have left redhat

### PR DESCRIPTION
**Pull request by akraitman**
Signed-off-by: Adam Kraitman <akraitma@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
Kefu is still active upstream, please leave his key

**Comment by akraitman** [comment]
> Kefu is still active upstream, please leave his key
okay I restored his key

**Comment by djgalloway** [comment]
We need to merge the ceph-sepia-secrets and ceph-octo-secrets PRs before we merge this or else we'll break the `users` role when it runs during teuthology jobs.

**Comment by akraitman** [comment]
> We need to merge the ceph-sepia-secrets and ceph-octo-secrets PRs before we merge this or else we'll break the `users` role when it runs during teuthology jobs.

Fixed the ceph-sepia-secrets MR and created MR for the ceph-octo-secrets

**Comment by dmick** [comment]
Has Warren left RH?

**Comment by akraitman** [comment]
> Has Warren left RH?
Yes, according to rover people and other places I have checked

**Pull request merged**
