### PR TITLE
Removing public keys of the users who has left RedHat

### PR DESCRIPTION
**Pull request by rakshithakamath94**

### CODE REVIEW

**Comment by dmick** [comment]
These users should also be added to the revoked_users list in ceph-sepia-secrets, surely, yes?

**Comment by rakshithakamath94** [comment]
Oh, I didn't know that. I will check with Adam on this.
Thanks Dan :)

**Comment by dmick** [comment]
I decided to put together a PR, but, now I'm looking...kchai and nhm?  True, they've left redhat, but are they not still working on Ceph as community developers?

**Comment by rakshithakamath94** [comment]
Hi @dmick,

I got the issue but all I have is their redhat email addresses and they no longer work at Redhat. If I have to send a mail to them asking if they would need the vpn, how can I contact them. I would like to send them an email asking if they need VPN but I am out of ways to reach out to them.

I was just searching through out GitHub to find them and I am getting many accounts for those names and I am not able to pin point the right one in order to send an email to them about if they need VPN or not.

**Comment by rakshithakamath94** [comment]
Ok, I found them.

**Comment by rakshithakamath94** [comment]
Started a thread on the slack channel regarding this issue. @dmick, please give me your POV there.

**Pull request merged**
