### PR TITLE
Delete departed user's keys

### PR DESCRIPTION
**Pull request by djgalloway**
Fixes: http://tracker.ceph.com/issues/14868

Signed-off-by: David Galloway dgallowa@redhat.com

### CODE REVIEW

**Comment by djgalloway** [comment]
@dmick Knower of all users, can you advise (or just remove) infra and user keys we no longer need/use please?

The ones I've removed are part of the purge in http://tracker.ceph.com/issues/14868

**Comment by zmc** [comment]
:thumbsup:

**Comment by dmick** [comment]
Any reason not to do this?

**Comment by djgalloway** [comment]
Fire away

**Pull request merged**
